spring.application.name=job-tracker-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/job_tracker_db
spring.datasource.username=postgres
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

server.port=8080

jwt.secret=jobtracker_surya_secret_key_2026_secure
jwt.expiration=86400000
